# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Desktop/Work/GUI/game_process_menu.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 785)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1440, 900))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Game_process_png.png"))
        self.label.setObjectName("label")
        self.Next_turn_button = QtWidgets.QPushButton(self.centralwidget)
        self.Next_turn_button.setGeometry(QtCore.QRect(580, 40, 281, 81))
        self.Next_turn_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Next_turn_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Next_turn_button_png.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Next_turn_button.setIcon(icon)
        self.Next_turn_button.setIconSize(QtCore.QSize(571, 111))
        self.Next_turn_button.setCheckable(True)
        self.Next_turn_button.setChecked(True)
        self.Next_turn_button.setFlat(False)
        self.Next_turn_button.setObjectName("Next_turn_button")
        self.Back_to_main_menu_button = QtWidgets.QPushButton(self.centralwidget)
        self.Back_to_main_menu_button.setGeometry(QtCore.QRect(0, 0, 291, 81))
        self.Back_to_main_menu_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Back_to_main_menu_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Back_to_main_menu_button_png.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Back_to_main_menu_button.setIcon(icon1)
        self.Back_to_main_menu_button.setIconSize(QtCore.QSize(291, 81))
        self.Back_to_main_menu_button.setObjectName("Back_to_main_menu_button")
        self.Card0 = QtWidgets.QPushButton(self.centralwidget)
        self.Card0.setGeometry(QtCore.QRect(560, 300, 321, 60))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.Card0.setFont(font)
        self.Card0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Card0.setText("")
        self.Card0.setIconSize(QtCore.QSize(321, 51))
        self.Card0.setFlat(True)
        self.Card0.setObjectName("Card")
        self.Card1 = QtWidgets.QPushButton(self.centralwidget)
        self.Card1.setGeometry(QtCore.QRect(560, 300 + 55, 321, 60))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.Card1.setFont(font)
        self.Card1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Card1.setText("")
        self.Card1.setIconSize(QtCore.QSize(321, 51))
        self.Card1.setFlat(True)
        self.Card1.setObjectName("Card")
        self.Card2 = QtWidgets.QPushButton(self.centralwidget)
        self.Card2.setGeometry(QtCore.QRect(560, 300 + 110, 321, 60))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.Card2.setFont(font)
        self.Card2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Card2.setText("")
        self.Card2.setIconSize(QtCore.QSize(321, 51))
        self.Card2.setFlat(True)
        self.Card2.setObjectName("Card")
        self.Card3 = QtWidgets.QPushButton(self.centralwidget)
        self.Card3.setGeometry(QtCore.QRect(560, 300 + 165, 321, 60))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.Card3.setFont(font)
        self.Card3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Card3.setText("")
        self.Card3.setIconSize(QtCore.QSize(321, 51))
        self.Card3.setFlat(True)
        self.Card3.setObjectName("Card")
        self.Card4 = QtWidgets.QPushButton(self.centralwidget)
        self.Card4.setGeometry(QtCore.QRect(560, 300 + 230, 321, 60))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.Card4.setFont(font)
        self.Card4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Card4.setText("")
        self.Card4.setIconSize(QtCore.QSize(321, 51))
        self.Card4.setFlat(True)
        self.Card4.setObjectName("Card")
        self.Card5 = QtWidgets.QPushButton(self.centralwidget)
        self.Card5.setGeometry(QtCore.QRect(560, 300 + 285, 321, 60))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.Card5.setFont(font)
        self.Card5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Card5.setText("")
        self.Card5.setIconSize(QtCore.QSize(321, 51))
        self.Card5.setFlat(True)
        self.Card5.setObjectName("Card")
        self.Card6 = QtWidgets.QPushButton(self.centralwidget)
        self.Card6.setGeometry(QtCore.QRect(560, 300 + 340, 321, 60))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.Card6.setFont(font)
        self.Card6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Card6.setText("")
        self.Card6.setIconSize(QtCore.QSize(321, 51))
        self.Card6.setFlat(True)
        self.Card6.setObjectName("Card")
        self.Card7 = QtWidgets.QPushButton(self.centralwidget)
        self.Card7.setGeometry(QtCore.QRect(560, 300 + 395, 321, 60))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.Card7.setFont(font)
        self.Card7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Card7.setText("")
        self.Card7.setIconSize(QtCore.QSize(321, 51))
        self.Card7.setFlat(True)
        self.Card7.setObjectName("Card")
        self.First_player_label = QtWidgets.QLabel(self.centralwidget)
        self.First_player_label.setGeometry(QtCore.QRect(110, 220, 351, 591))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.First_player_label.setFont(font)
        self.First_player_label.setText("")
        self.First_player_label.setObjectName("First_player_label")
        self.Second_player_label = QtWidgets.QLabel(self.centralwidget)
        self.Second_player_label.setGeometry(QtCore.QRect(1039, 215, 351, 601))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.Second_player_label.setFont(font)        
        self.Second_player_label.setText("")
        self.Second_player_label.setObjectName("Second_player_label")
        self.Refresh_button = QtWidgets.QPushButton(self.centralwidget)
        self.Refresh_button.setGeometry(QtCore.QRect(1070, 10, 281, 81))
        self.Refresh_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Refresh_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Refresh_button_png.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Refresh_button.setIcon(icon2)
        self.Refresh_button.setIconSize(QtCore.QSize(281, 81))
        self.Refresh_button.setObjectName("Refresh_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


